# Generated by Django 4.2.7 on 2023-11-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.TextField(verbose_name='Аеропорт відправки')),
                ('arrival', models.TextField(verbose_name='Аеропорт прибуття')),
                ('departure_date_time', models.DateTimeField(verbose_name='Дата та час відправки')),
                ('arrival_date_time', models.DateTimeField(verbose_name='Дата та час прибуття')),
                ('duration', models.DurationField(verbose_name='Тривалість')),
                ('cost_base', models.IntegerField(verbose_name='Базова вартість')),
                ('cost_regular', models.IntegerField(verbose_name='Вартість до 10 кг багажу')),
                ('cost_plus', models.IntegerField(verbose_name='Вартість до 20 кг багажу')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейси',
            },
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(verbose_name='Модель')),
                ('passengers', models.IntegerField(verbose_name='Пасажири')),
                ('plane_layout', models.BinaryField(verbose_name='Розташування місць')),
            ],
            options={
                'verbose_name': 'Літак',
                'verbose_name_plural': 'Літаки',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(verbose_name='Но')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botapp.flight', verbose_name='')),
            ],
            options={
                'verbose_name': 'Місце',
                'verbose_name_plural': 'Місця',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botapp.flight', verbose_name='')),
                ('plane_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botapp.plane', verbose_name='')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botapp.seat', verbose_name='')),
            ],
            options={
                'verbose_name': 'Білет',
                'verbose_name_plural': 'Білети',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name="Ім'я користувача")),
                ('surname', models.TextField(verbose_name='Прізвище користувача')),
                ('sex', models.TextField(verbose_name='Стать')),
                ('phone_number', models.TextField(verbose_name='Номер телефону')),
                ('email', models.TextField(verbose_name='Електронна пошта')),
            ],
            options={
                'verbose_name': 'Інформація про користувача',
                'verbose_name_plural': 'Інформація про користувачів',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(verbose_name='Чат')),
                ('save_info', models.BooleanField(verbose_name='Зберегти особисті данні ?')),
                ('ticket', models.ManyToManyField(to='botapp.ticket')),
                ('user_info_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='botapp.userinfo', verbose_name='Інформація о користувачі')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='user_info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botapp.userinfo', verbose_name=''),
        ),
        migrations.AddField(
            model_name='flight',
            name='plane_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botapp.plane', verbose_name='Літак'),
        ),
    ]
